name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build and export
      run: npm run build
      env:
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
        NODE_ENV: production
    
    - name: Deploy to S3
      run: |
        aws s3 sync ./out s3://${{ secrets.S3_BUCKET_NAME }} \
          --delete \
          --cache-control "public,max-age=31536000,immutable" \
          --exclude "*.html" \
          --exclude "manifest.json"
        aws s3 sync ./out s3://${{ secrets.S3_BUCKET_NAME }} \
          --delete \
          --cache-control "public,max-age=0,must-revalidate" \
          --exclude "*" \
          --include "*.html" \
          --include "manifest.json" \
          --content-type "text/html; charset=utf-8"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} \
          --paths "/*"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

